name: Simple GitHub Action

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: 24ds3000006@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Show completion message
        run: echo "The GitHub Action ran successfully."
